### ISSUE TITLE
Rate Limiting on Import

### ISSUE THREAD

**Issue by kwhite** [gavinr/github-csv-tools#3]
Hi there! Me again...

So the throttling is better but I was apparently still too liberal. I'm still hitting rate limit issues with the current configuration (my test case is about 78 issues that I am importing, FYI).

Also, I'm checking for items in the queue before exiting the program but if I have requests that lag, it aborts early. So that needs adjusting too.

I will work on it and send you another PR; just wanted to let you know in case you get to it first.

**Comment by gavinr** [comment]
Now using octokit and https://github.com/octokit/plugin-throttling.js

**Comment by mattip** [comment]
Apparently there is a different endpoint for issue creation at `https://api.github.com/repos/${GITHUB_USERNAME}/${GIHUB_REPONAME}/import/issues`, see [this gist](https://gist.github.com/jonmagic/5282384165e0f86ef105). Since it does not send notifications, it is not subject to the secondary rate limit. I found this by asking github support. xref https://github.com/piceaTech/node-gitlab-2-github/issues/28.

**Comment by gavinr** [comment]
Thanks for the input. PRs welcome to switch it to use that other API endpoint.
