### ISSUE TITLE
Importing to specific projects

### ISSUE THREAD

**Issue by PawelWkl** [gavinr/github-csv-tools#31]
Is there any way to import issues to the specific project that is linked to many repositories?

**Comment by gavinr** [comment]
I'm not sure what you mean - could you please clarify or give more details on your situation? Thanks!

**Comment by PawelWkl** [comment]
Sorry, not a daily GitHub user. Organization has many repositories but the project is not in the repo but on the level of organization. This project is linked to many repositories and when I import the issues, I have to choose the repo but have no possibility to assign it to the project, so I have to do it manually after the issues are uploaded to the repo.
Like in the attached file - I would love to import issues to the Engineering backlog.
![Screenshot 2020-09-17 at 09 04 34](https://user-images.githubusercontent.com/13221374/93431725-d475f480-f8c4-11ea-8f10-2d1b2f7dfe4b.png)

**Comment by gavinr** [comment]
I think this might be a big effort because you'd have to define which CSV column has the project ID and then also which "Project Column" it should be imported into. For now I'd say this is out of scope for this project, but if there is a lot of requests for this in the long term I'd be open to a PR eventually.

**Comment by MarkvV** [comment]
Well. I actually started using your tool to migrate issues from Gitlab to Github (after some manual CSV editing). However I also want to import the entire CSV into a project and not a repository, necessarily.
